
package ihe.iti.pdqv3._2007;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.naming.spi.ObjectFactory;
import javax.xml.bind.annotation.XmlSeeAlso;

import org.hl7.v3.MCCIIN000002UV01;
import org.hl7.v3.PRPAIN201305UV02;
import org.hl7.v3.PRPAIN201306UV02;
import org.hl7.v3.QUQIIN000003UV01Type;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PDQSupplier_PortType", targetNamespace = "urn:ihe:iti:pdqv3:2007")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PDQSupplierPortType {


    /**
     * 
     * @param body
     * @return
     *     returns org.hl7.v3.PRPAIN201306UV02
     */
    @WebMethod(operationName = "PDQSupplier_PRPA_IN201305UV02", action = "urn:hl7-org:v3:PRPA_IN201305UV02")
    @WebResult(name = "PRPA_IN201306UV02", targetNamespace = "urn:hl7-org:v3", partName = "Body")
    public PRPAIN201306UV02 pdqSupplierPRPAIN201305UV02(
        @WebParam(name = "PRPA_IN201305UV02", targetNamespace = "urn:hl7-org:v3", partName = "Body")
        PRPAIN201305UV02 body);

    /**
     * 
     * @param body
     * @return
     *     returns org.hl7.v3.PRPAIN201306UV02
     */
    @WebMethod(operationName = "PDQSupplier_QUQI_IN000003UV01_Continue", action = "urn:hl7-org:v3:QUQI_IN000003UV01_Continue")
    @WebResult(name = "PRPA_IN201306UV02", targetNamespace = "urn:hl7-org:v3", partName = "Body")
    public PRPAIN201306UV02 pdqSupplierQUQIIN000003UV01Continue(
        @WebParam(name = "QUQI_IN000003UV01", targetNamespace = "urn:hl7-org:v3", partName = "Body")
        QUQIIN000003UV01Type body);

    /**
     * 
     * @param body
     * @return
     *     returns org.hl7.v3.MCCIIN000002UV01
     */
    @WebMethod(operationName = "PDQSupplier_QUQI_IN000003UV01_Cancel", action = "urn:hl7-org:v3: QUQI_IN000003UV01_Cancel")
    @WebResult(name = "MCCI_IN000002UV01", targetNamespace = "urn:hl7-org:v3", partName = "Body")
    public MCCIIN000002UV01 pdqSupplierQUQIIN000003UV01Cancel(
        @WebParam(name = "QUQI_IN000003UV01_Cancel", targetNamespace = "urn:hl7-org:v3", partName = "Body")
        QUQIIN000003UV01Type body);

}
