
package ihe.iti.pdqv3._2007;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PDQSupplier_Service", targetNamespace = "urn:ihe:iti:pdqv3:2007", wsdlLocation = ": https://servicoshm.saude.gov.br/cadsus/PDQSupplier.wsdl")
public class PDQSupplierService
    extends Service
{

    private final static URL PDQSUPPLIERSERVICE_WSDL_LOCATION;
    private final static WebServiceException PDQSUPPLIERSERVICE_EXCEPTION;
    private final static QName PDQSUPPLIERSERVICE_QNAME = new QName("urn:ihe:iti:pdqv3:2007", "PDQSupplier_Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://servicoshm.saude.gov.br/cadsus/PDQSupplier");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PDQSUPPLIERSERVICE_WSDL_LOCATION = url;
        PDQSUPPLIERSERVICE_EXCEPTION = e;
    }

    public PDQSupplierService() {
        super(__getWsdlLocation(), PDQSUPPLIERSERVICE_QNAME);
    }

    public PDQSupplierService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PDQSUPPLIERSERVICE_QNAME, features);
    }

    public PDQSupplierService(URL wsdlLocation) {
        super(wsdlLocation, PDQSUPPLIERSERVICE_QNAME);
    }

    public PDQSupplierService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PDQSUPPLIERSERVICE_QNAME, features);
    }

    public PDQSupplierService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PDQSupplierService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PDQSupplierPortType
     */
    @WebEndpoint(name = "PDQSupplier_Port_Soap12")
    public PDQSupplierPortType getPDQSupplierPortSoap12() {
        return super.getPort(new QName("urn:ihe:iti:pdqv3:2007", "PDQSupplier_Port_Soap12"), PDQSupplierPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PDQSupplierPortType
     */
    @WebEndpoint(name = "PDQSupplier_Port_Soap12")
    public PDQSupplierPortType getPDQSupplierPortSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("urn:ihe:iti:pdqv3:2007", "PDQSupplier_Port_Soap12"), PDQSupplierPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PDQSUPPLIERSERVICE_EXCEPTION!= null) {
            throw PDQSUPPLIERSERVICE_EXCEPTION;
        }
        return PDQSUPPLIERSERVICE_WSDL_LOCATION;
    }

}
