
package ihe.iti.pixv3._2007;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.naming.spi.ObjectFactory;
import javax.xml.bind.annotation.XmlSeeAlso;

import org.hl7.v3.MCCIIN000002UV01;
import org.hl7.v3.PRPAIN201301UV02;
import org.hl7.v3.PRPAIN201302UV02;
import org.hl7.v3.PRPAIN201304UV02;
import org.hl7.v3.PRPAIN201309UV02;
import org.hl7.v3.PRPAIN201310UV02;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PIXManager_PortType", targetNamespace = "urn:ihe:iti:pixv3:2007")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PIXManagerPortType {


    /**
     * 
     * @param body
     * @return
     *     returns org.hl7.v3.MCCIIN000002UV01
     */
    @WebMethod(operationName = "PIXManager_PRPA_IN201301UV02", action = "urn:hl7-org:v3:PRPA_IN201301UV02")
    @WebResult(name = "MCCI_IN000002UV01", targetNamespace = "urn:hl7-org:v3", partName = "Body")
    public MCCIIN000002UV01 pixManagerPRPAIN201301UV02(
        @WebParam(name = "PRPA_IN201301UV02", targetNamespace = "urn:hl7-org:v3", partName = "Body")
        PRPAIN201301UV02 body);

    /**
     * 
     * @param body
     * @return
     *     returns org.hl7.v3.MCCIIN000002UV01
     */
    @WebMethod(operationName = "PIXManager_PRPA_IN201302UV02", action = "urn:hl7-org:v3:PRPA_IN201302UV02")
    @WebResult(name = "MCCI_IN000002UV01", targetNamespace = "urn:hl7-org:v3", partName = "Body")
    public MCCIIN000002UV01 pixManagerPRPAIN201302UV02(
        @WebParam(name = "PRPA_IN201302UV02", targetNamespace = "urn:hl7-org:v3", partName = "Body")
        PRPAIN201302UV02 body);

    /**
     * 
     * @param body
     * @return
     *     returns org.hl7.v3.MCCIIN000002UV01
     */
    @WebMethod(operationName = "PIXManager_PRPA_IN201304UV02", action = "urn:hl7-org:v3:PRPA_IN201304UV02")
    @WebResult(name = "MCCI_IN000002UV01", targetNamespace = "urn:hl7-org:v3", partName = "Body")
    public MCCIIN000002UV01 pixManagerPRPAIN201304UV02(
        @WebParam(name = "PRPA_IN201304UV02", targetNamespace = "urn:hl7-org:v3", partName = "Body")
        PRPAIN201304UV02 body);

    /**
     * 
     * @param body
     * @return
     *     returns org.hl7.v3.PRPAIN201310UV02
     */
    @WebMethod(operationName = "PIXManager_PRPA_IN201309UV02", action = "urn:hl7-org:v3:PRPA_IN201309UV02")
    @WebResult(name = "PRPA_IN201310UV02", targetNamespace = "urn:hl7-org:v3", partName = "Body")
    public PRPAIN201310UV02 pixManagerPRPAIN201309UV02(
        @WebParam(name = "PRPA_IN201309UV02", targetNamespace = "urn:hl7-org:v3", partName = "Body")
        PRPAIN201309UV02 body);

}
